// auto generated by struct_info_parser.py, please DO NOT edit!!!

#ifndef LONGFIST_PRINT_UTILS_H
#define LONGFIST_PRINT_UTILS_H

#include "LFUtils.h"

#include <iostream>
#include <iomanip>
#include <utility>

namespace LF_UTIL_PRINTER_CTP
{
	#include "../api/ctp/v6.3.6_20160606/include/ThostFtdcUserApiStruct.h"
}

// Macro to print struct content
#define PRINT_MD(ptr) ""\
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c13)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "ExchangeInstID:" << std::setw(6) << "(c64)" << " " << ptr->ExchangeInstID << std::endl \
	 << std::setw(20) << "LastPrice:" << std::setw(6) << "(d)" << " " << ptr->LastPrice << std::endl \
	 << std::setw(20) << "PreSettlementPrice:" << std::setw(6) << "(d)" << " " << ptr->PreSettlementPrice << std::endl \
	 << std::setw(20) << "PreClosePrice:" << std::setw(6) << "(d)" << " " << ptr->PreClosePrice << std::endl \
	 << std::setw(20) << "PreOpenInterest:" << std::setw(6) << "(d)" << " " << ptr->PreOpenInterest << std::endl \
	 << std::setw(20) << "OpenPrice:" << std::setw(6) << "(d)" << " " << ptr->OpenPrice << std::endl \
	 << std::setw(20) << "HighestPrice:" << std::setw(6) << "(d)" << " " << ptr->HighestPrice << std::endl \
	 << std::setw(20) << "LowestPrice:" << std::setw(6) << "(d)" << " " << ptr->LowestPrice << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(i)" << " " << (int)ptr->Volume << std::endl \
	 << std::setw(20) << "Turnover:" << std::setw(6) << "(d)" << " " << ptr->Turnover << std::endl \
	 << std::setw(20) << "OpenInterest:" << std::setw(6) << "(d)" << " " << ptr->OpenInterest << std::endl \
	 << std::setw(20) << "ClosePrice:" << std::setw(6) << "(d)" << " " << ptr->ClosePrice << std::endl \
	 << std::setw(20) << "SettlementPrice:" << std::setw(6) << "(d)" << " " << ptr->SettlementPrice << std::endl \
	 << std::setw(20) << "UpperLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->UpperLimitPrice << std::endl \
	 << std::setw(20) << "LowerLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LowerLimitPrice << std::endl \
	 << std::setw(20) << "PreDelta:" << std::setw(6) << "(d)" << " " << ptr->PreDelta << std::endl \
	 << std::setw(20) << "CurrDelta:" << std::setw(6) << "(d)" << " " << ptr->CurrDelta << std::endl \
	 << std::setw(20) << "UpdateTime:" << std::setw(6) << "(c13)" << " " << ptr->UpdateTime << std::endl \
	 << std::setw(20) << "UpdateMillisec:" << std::setw(6) << "(i)" << " " << (int)ptr->UpdateMillisec << std::endl \
	 << std::setw(20) << "BidPrice1:" << std::setw(6) << "(d)" << " " << ptr->BidPrice1 << std::endl \
	 << std::setw(20) << "BidVolume1:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume1 << std::endl \
	 << std::setw(20) << "AskPrice1:" << std::setw(6) << "(d)" << " " << ptr->AskPrice1 << std::endl \
	 << std::setw(20) << "AskVolume1:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume1 << std::endl \
	 << std::setw(20) << "BidPrice2:" << std::setw(6) << "(d)" << " " << ptr->BidPrice2 << std::endl \
	 << std::setw(20) << "BidVolume2:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume2 << std::endl \
	 << std::setw(20) << "AskPrice2:" << std::setw(6) << "(d)" << " " << ptr->AskPrice2 << std::endl \
	 << std::setw(20) << "AskVolume2:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume2 << std::endl \
	 << std::setw(20) << "BidPrice3:" << std::setw(6) << "(d)" << " " << ptr->BidPrice3 << std::endl \
	 << std::setw(20) << "BidVolume3:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume3 << std::endl \
	 << std::setw(20) << "AskPrice3:" << std::setw(6) << "(d)" << " " << ptr->AskPrice3 << std::endl \
	 << std::setw(20) << "AskVolume3:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume3 << std::endl \
	 << std::setw(20) << "BidPrice4:" << std::setw(6) << "(d)" << " " << ptr->BidPrice4 << std::endl \
	 << std::setw(20) << "BidVolume4:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume4 << std::endl \
	 << std::setw(20) << "AskPrice4:" << std::setw(6) << "(d)" << " " << ptr->AskPrice4 << std::endl \
	 << std::setw(20) << "AskVolume4:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume4 << std::endl \
	 << std::setw(20) << "BidPrice5:" << std::setw(6) << "(d)" << " " << ptr->BidPrice5 << std::endl \
	 << std::setw(20) << "BidVolume5:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume5 << std::endl \
	 << std::setw(20) << "AskPrice5:" << std::setw(6) << "(d)" << " " << ptr->AskPrice5 << std::endl \
	 << std::setw(20) << "AskVolume5:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume5 << std::endl \
	
#define PRINT_L2_MD(ptr) ""\
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c9)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "TimeStamp:" << std::setw(6) << "(c9)" << " " << ptr->TimeStamp << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "PreClosePrice:" << std::setw(6) << "(d)" << " " << ptr->PreClosePrice << std::endl \
	 << std::setw(20) << "OpenPrice:" << std::setw(6) << "(d)" << " " << ptr->OpenPrice << std::endl \
	 << std::setw(20) << "ClosePrice:" << std::setw(6) << "(d)" << " " << ptr->ClosePrice << std::endl \
	 << std::setw(20) << "IOPV:" << std::setw(6) << "(d)" << " " << ptr->IOPV << std::endl \
	 << std::setw(20) << "YieldToMaturity:" << std::setw(6) << "(d)" << " " << ptr->YieldToMaturity << std::endl \
	 << std::setw(20) << "AuctionPrice:" << std::setw(6) << "(d)" << " " << ptr->AuctionPrice << std::endl \
	 << std::setw(20) << "TradingPhase:" << std::setw(6) << "(c)" << " " << ptr->TradingPhase << std::endl \
	 << std::setw(20) << "OpenRestriction:" << std::setw(6) << "(c)" << " " << ptr->OpenRestriction << std::endl \
	 << std::setw(20) << "HighPrice:" << std::setw(6) << "(d)" << " " << ptr->HighPrice << std::endl \
	 << std::setw(20) << "LowPrice:" << std::setw(6) << "(d)" << " " << ptr->LowPrice << std::endl \
	 << std::setw(20) << "LastPrice:" << std::setw(6) << "(d)" << " " << ptr->LastPrice << std::endl \
	 << std::setw(20) << "TradeCount:" << std::setw(6) << "(d)" << " " << ptr->TradeCount << std::endl \
	 << std::setw(20) << "TotalTradeVolume:" << std::setw(6) << "(d)" << " " << ptr->TotalTradeVolume << std::endl \
	 << std::setw(20) << "TotalTradeValue:" << std::setw(6) << "(d)" << " " << ptr->TotalTradeValue << std::endl \
	 << std::setw(20) << "OpenInterest:" << std::setw(6) << "(d)" << " " << ptr->OpenInterest << std::endl \
	 << std::setw(20) << "TotalBidVolume:" << std::setw(6) << "(d)" << " " << ptr->TotalBidVolume << std::endl \
	 << std::setw(20) << "WeightedAvgBidPrice:" << std::setw(6) << "(d)" << " " << ptr->WeightedAvgBidPrice << std::endl \
	 << std::setw(20) << "AltWeightedAvgBidPrice:" << std::setw(6) << "(d)" << " " << ptr->AltWeightedAvgBidPrice << std::endl \
	 << std::setw(20) << "TotalOfferVolume:" << std::setw(6) << "(d)" << " " << ptr->TotalOfferVolume << std::endl \
	 << std::setw(20) << "WeightedAvgOfferPrice:" << std::setw(6) << "(d)" << " " << ptr->WeightedAvgOfferPrice << std::endl \
	 << std::setw(20) << "AltWeightedAvgOfferPrice:" << std::setw(6) << "(d)" << " " << ptr->AltWeightedAvgOfferPrice << std::endl \
	 << std::setw(20) << "BidPriceLevel:" << std::setw(6) << "(i)" << " " << (int)ptr->BidPriceLevel << std::endl \
	 << std::setw(20) << "OfferPriceLevel:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferPriceLevel << std::endl \
	 << std::setw(20) << "BidPrice1:" << std::setw(6) << "(d)" << " " << ptr->BidPrice1 << std::endl \
	 << std::setw(20) << "BidVolume1:" << std::setw(6) << "(d)" << " " << ptr->BidVolume1 << std::endl \
	 << std::setw(20) << "BidCount1:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount1 << std::endl \
	 << std::setw(20) << "BidPrice2:" << std::setw(6) << "(d)" << " " << ptr->BidPrice2 << std::endl \
	 << std::setw(20) << "BidVolume2:" << std::setw(6) << "(d)" << " " << ptr->BidVolume2 << std::endl \
	 << std::setw(20) << "BidCount2:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount2 << std::endl \
	 << std::setw(20) << "BidPrice3:" << std::setw(6) << "(d)" << " " << ptr->BidPrice3 << std::endl \
	 << std::setw(20) << "BidVolume3:" << std::setw(6) << "(d)" << " " << ptr->BidVolume3 << std::endl \
	 << std::setw(20) << "BidCount3:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount3 << std::endl \
	 << std::setw(20) << "BidPrice4:" << std::setw(6) << "(d)" << " " << ptr->BidPrice4 << std::endl \
	 << std::setw(20) << "BidVolume4:" << std::setw(6) << "(d)" << " " << ptr->BidVolume4 << std::endl \
	 << std::setw(20) << "BidCount4:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount4 << std::endl \
	 << std::setw(20) << "BidPrice5:" << std::setw(6) << "(d)" << " " << ptr->BidPrice5 << std::endl \
	 << std::setw(20) << "BidVolume5:" << std::setw(6) << "(d)" << " " << ptr->BidVolume5 << std::endl \
	 << std::setw(20) << "BidCount5:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount5 << std::endl \
	 << std::setw(20) << "BidPrice6:" << std::setw(6) << "(d)" << " " << ptr->BidPrice6 << std::endl \
	 << std::setw(20) << "BidVolume6:" << std::setw(6) << "(d)" << " " << ptr->BidVolume6 << std::endl \
	 << std::setw(20) << "BidCount6:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount6 << std::endl \
	 << std::setw(20) << "BidPrice7:" << std::setw(6) << "(d)" << " " << ptr->BidPrice7 << std::endl \
	 << std::setw(20) << "BidVolume7:" << std::setw(6) << "(d)" << " " << ptr->BidVolume7 << std::endl \
	 << std::setw(20) << "BidCount7:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount7 << std::endl \
	 << std::setw(20) << "BidPrice8:" << std::setw(6) << "(d)" << " " << ptr->BidPrice8 << std::endl \
	 << std::setw(20) << "BidVolume8:" << std::setw(6) << "(d)" << " " << ptr->BidVolume8 << std::endl \
	 << std::setw(20) << "BidCount8:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount8 << std::endl \
	 << std::setw(20) << "BidPrice9:" << std::setw(6) << "(d)" << " " << ptr->BidPrice9 << std::endl \
	 << std::setw(20) << "BidVolume9:" << std::setw(6) << "(d)" << " " << ptr->BidVolume9 << std::endl \
	 << std::setw(20) << "BidCount9:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCount9 << std::endl \
	 << std::setw(20) << "BidPriceA:" << std::setw(6) << "(d)" << " " << ptr->BidPriceA << std::endl \
	 << std::setw(20) << "BidVolumeA:" << std::setw(6) << "(d)" << " " << ptr->BidVolumeA << std::endl \
	 << std::setw(20) << "BidCountA:" << std::setw(6) << "(i)" << " " << (int)ptr->BidCountA << std::endl \
	 << std::setw(20) << "OfferPrice1:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice1 << std::endl \
	 << std::setw(20) << "OfferVolume1:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume1 << std::endl \
	 << std::setw(20) << "OfferCount1:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount1 << std::endl \
	 << std::setw(20) << "OfferPrice2:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice2 << std::endl \
	 << std::setw(20) << "OfferVolume2:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume2 << std::endl \
	 << std::setw(20) << "OfferCount2:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount2 << std::endl \
	 << std::setw(20) << "OfferPrice3:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice3 << std::endl \
	 << std::setw(20) << "OfferVolume3:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume3 << std::endl \
	 << std::setw(20) << "OfferCount3:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount3 << std::endl \
	 << std::setw(20) << "OfferPrice4:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice4 << std::endl \
	 << std::setw(20) << "OfferVolume4:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume4 << std::endl \
	 << std::setw(20) << "OfferCount4:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount4 << std::endl \
	 << std::setw(20) << "OfferPrice5:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice5 << std::endl \
	 << std::setw(20) << "OfferVolume5:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume5 << std::endl \
	 << std::setw(20) << "OfferCount5:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount5 << std::endl \
	 << std::setw(20) << "OfferPrice6:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice6 << std::endl \
	 << std::setw(20) << "OfferVolume6:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume6 << std::endl \
	 << std::setw(20) << "OfferCount6:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount6 << std::endl \
	 << std::setw(20) << "OfferPrice7:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice7 << std::endl \
	 << std::setw(20) << "OfferVolume7:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume7 << std::endl \
	 << std::setw(20) << "OfferCount7:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount7 << std::endl \
	 << std::setw(20) << "OfferPrice8:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice8 << std::endl \
	 << std::setw(20) << "OfferVolume8:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume8 << std::endl \
	 << std::setw(20) << "OfferCount8:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount8 << std::endl \
	 << std::setw(20) << "OfferPrice9:" << std::setw(6) << "(d)" << " " << ptr->OfferPrice9 << std::endl \
	 << std::setw(20) << "OfferVolume9:" << std::setw(6) << "(d)" << " " << ptr->OfferVolume9 << std::endl \
	 << std::setw(20) << "OfferCount9:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCount9 << std::endl \
	 << std::setw(20) << "OfferPriceA:" << std::setw(6) << "(d)" << " " << ptr->OfferPriceA << std::endl \
	 << std::setw(20) << "OfferVolumeA:" << std::setw(6) << "(d)" << " " << ptr->OfferVolumeA << std::endl \
	 << std::setw(20) << "OfferCountA:" << std::setw(6) << "(i)" << " " << (int)ptr->OfferCountA << std::endl \
	 << std::setw(20) << "InstrumentStatus:" << std::setw(6) << "(c7)" << " " << ptr->InstrumentStatus << std::endl \
	 << std::setw(20) << "PreIOPV:" << std::setw(6) << "(d)" << " " << ptr->PreIOPV << std::endl \
	 << std::setw(20) << "PERatio1:" << std::setw(6) << "(d)" << " " << ptr->PERatio1 << std::endl \
	 << std::setw(20) << "PERatio2:" << std::setw(6) << "(d)" << " " << ptr->PERatio2 << std::endl \
	 << std::setw(20) << "UpperLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->UpperLimitPrice << std::endl \
	 << std::setw(20) << "LowerLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LowerLimitPrice << std::endl \
	 << std::setw(20) << "WarrantPremiumRatio:" << std::setw(6) << "(d)" << " " << ptr->WarrantPremiumRatio << std::endl \
	 << std::setw(20) << "TotalWarrantExecQty:" << std::setw(6) << "(d)" << " " << ptr->TotalWarrantExecQty << std::endl \
	 << std::setw(20) << "PriceDiff1:" << std::setw(6) << "(d)" << " " << ptr->PriceDiff1 << std::endl \
	 << std::setw(20) << "PriceDiff2:" << std::setw(6) << "(d)" << " " << ptr->PriceDiff2 << std::endl \
	 << std::setw(20) << "ETFBuyNumber:" << std::setw(6) << "(d)" << " " << ptr->ETFBuyNumber << std::endl \
	 << std::setw(20) << "ETFBuyAmount:" << std::setw(6) << "(d)" << " " << ptr->ETFBuyAmount << std::endl \
	 << std::setw(20) << "ETFBuyMoney:" << std::setw(6) << "(d)" << " " << ptr->ETFBuyMoney << std::endl \
	 << std::setw(20) << "ETFSellNumber:" << std::setw(6) << "(d)" << " " << ptr->ETFSellNumber << std::endl \
	 << std::setw(20) << "ETFSellAmount:" << std::setw(6) << "(d)" << " " << ptr->ETFSellAmount << std::endl \
	 << std::setw(20) << "ETFSellMoney:" << std::setw(6) << "(d)" << " " << ptr->ETFSellMoney << std::endl \
	 << std::setw(20) << "WithdrawBuyNumber:" << std::setw(6) << "(d)" << " " << ptr->WithdrawBuyNumber << std::endl \
	 << std::setw(20) << "WithdrawBuyAmount:" << std::setw(6) << "(d)" << " " << ptr->WithdrawBuyAmount << std::endl \
	 << std::setw(20) << "WithdrawBuyMoney:" << std::setw(6) << "(d)" << " " << ptr->WithdrawBuyMoney << std::endl \
	 << std::setw(20) << "TotalBidNumber:" << std::setw(6) << "(d)" << " " << ptr->TotalBidNumber << std::endl \
	 << std::setw(20) << "BidTradeMaxDuration:" << std::setw(6) << "(d)" << " " << ptr->BidTradeMaxDuration << std::endl \
	 << std::setw(20) << "NumBidOrders:" << std::setw(6) << "(d)" << " " << ptr->NumBidOrders << std::endl \
	 << std::setw(20) << "WithdrawSellNumber:" << std::setw(6) << "(d)" << " " << ptr->WithdrawSellNumber << std::endl \
	 << std::setw(20) << "WithdrawSellAmount:" << std::setw(6) << "(d)" << " " << ptr->WithdrawSellAmount << std::endl \
	 << std::setw(20) << "WithdrawSellMoney:" << std::setw(6) << "(d)" << " " << ptr->WithdrawSellMoney << std::endl \
	 << std::setw(20) << "TotalOfferNumber:" << std::setw(6) << "(d)" << " " << ptr->TotalOfferNumber << std::endl \
	 << std::setw(20) << "OfferTradeMaxDuration:" << std::setw(6) << "(d)" << " " << ptr->OfferTradeMaxDuration << std::endl \
	 << std::setw(20) << "NumOfferOrders:" << std::setw(6) << "(d)" << " " << ptr->NumOfferOrders << std::endl \
	
#define PRINT_L2_INDEX(ptr) ""\
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c9)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "TimeStamp:" << std::setw(6) << "(c9)" << " " << ptr->TimeStamp << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "PreCloseIndex:" << std::setw(6) << "(d)" << " " << ptr->PreCloseIndex << std::endl \
	 << std::setw(20) << "OpenIndex:" << std::setw(6) << "(d)" << " " << ptr->OpenIndex << std::endl \
	 << std::setw(20) << "CloseIndex:" << std::setw(6) << "(d)" << " " << ptr->CloseIndex << std::endl \
	 << std::setw(20) << "HighIndex:" << std::setw(6) << "(d)" << " " << ptr->HighIndex << std::endl \
	 << std::setw(20) << "LowIndex:" << std::setw(6) << "(d)" << " " << ptr->LowIndex << std::endl \
	 << std::setw(20) << "LastIndex:" << std::setw(6) << "(d)" << " " << ptr->LastIndex << std::endl \
	 << std::setw(20) << "TurnOver:" << std::setw(6) << "(d)" << " " << ptr->TurnOver << std::endl \
	 << std::setw(20) << "TotalVolume:" << std::setw(6) << "(d)" << " " << ptr->TotalVolume << std::endl \
	
#define PRINT_L2_ORDER(ptr) ""\
	 << std::setw(20) << "OrderTime:" << std::setw(6) << "(c9)" << " " << ptr->OrderTime << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "Price:" << std::setw(6) << "(d)" << " " << ptr->Price << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(d)" << " " << ptr->Volume << std::endl \
	 << std::setw(20) << "OrderKind:" << std::setw(6) << "(c2)" << " " << ptr->OrderKind << std::endl \
	
#define PRINT_L2_TRADE(ptr) ""\
	 << std::setw(20) << "TradeTime:" << std::setw(6) << "(c9)" << " " << ptr->TradeTime << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "Price:" << std::setw(6) << "(d)" << " " << ptr->Price << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(d)" << " " << ptr->Volume << std::endl \
	 << std::setw(20) << "OrderKind:" << std::setw(6) << "(c2)" << " " << ptr->OrderKind << std::endl \
	 << std::setw(20) << "OrderBSFlag:" << std::setw(6) << "(c2)" << " " << ptr->OrderBSFlag << std::endl \
	
#define PRINT_BAR_MD(ptr) ""\
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c9)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "UpperLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->UpperLimitPrice << std::endl \
	 << std::setw(20) << "LowerLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LowerLimitPrice << std::endl \
	 << std::setw(20) << "StartUpdateTime:" << std::setw(6) << "(c13)" << " " << ptr->StartUpdateTime << std::endl \
	 << std::setw(20) << "StartUpdateMillisec:" << std::setw(6) << "(i)" << " " << (int)ptr->StartUpdateMillisec << std::endl \
	 << std::setw(20) << "EndUpdateTime:" << std::setw(6) << "(c13)" << " " << ptr->EndUpdateTime << std::endl \
	 << std::setw(20) << "EndUpdateMillisec:" << std::setw(6) << "(i)" << " " << (int)ptr->EndUpdateMillisec << std::endl \
	 << std::setw(20) << "Open:" << std::setw(6) << "(d)" << " " << ptr->Open << std::endl \
	 << std::setw(20) << "Close:" << std::setw(6) << "(d)" << " " << ptr->Close << std::endl \
	 << std::setw(20) << "Low:" << std::setw(6) << "(d)" << " " << ptr->Low << std::endl \
	 << std::setw(20) << "High:" << std::setw(6) << "(d)" << " " << ptr->High << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(d)" << " " << ptr->Volume << std::endl \
	 << std::setw(20) << "StartVolume:" << std::setw(6) << "(d)" << " " << ptr->StartVolume << std::endl \
	
#define PRINT_QRY_POS(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	
#define PRINT_RSP_POS(ptr) ""\
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "YdPosition:" << std::setw(6) << "(i)" << " " << (int)ptr->YdPosition << std::endl \
	 << std::setw(20) << "Position:" << std::setw(6) << "(i)" << " " << (int)ptr->Position << std::endl \
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "PositionCost:" << std::setw(6) << "(d)" << " " << ptr->PositionCost << std::endl \
	 << std::setw(20) << "HedgeFlag:" << std::setw(6) << "(t)" << " " << getLfHedgeFlagType(ptr->HedgeFlag) << std::endl \
	 << std::setw(20) << "PosiDirection:" << std::setw(6) << "(t)" << " " << getLfPosiDirectionType(ptr->PosiDirection) << std::endl \
	
#define PRINT_ORDER(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "BusinessUnit:" << std::setw(6) << "(c21)" << " " << ptr->BusinessUnit << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c21)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "LimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LimitPrice << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(i)" << " " << (int)ptr->Volume << std::endl \
	 << std::setw(20) << "MinVolume:" << std::setw(6) << "(i)" << " " << (int)ptr->MinVolume << std::endl \
	 << std::setw(20) << "TimeCondition:" << std::setw(6) << "(t)" << " " << getLfTimeConditionType(ptr->TimeCondition) << std::endl \
	 << std::setw(20) << "VolumeCondition:" << std::setw(6) << "(t)" << " " << getLfVolumeConditionType(ptr->VolumeCondition) << std::endl \
	 << std::setw(20) << "OrderPriceType:" << std::setw(6) << "(t)" << " " << getLfOrderPriceTypeType(ptr->OrderPriceType) << std::endl \
	 << std::setw(20) << "Direction:" << std::setw(6) << "(t)" << " " << getLfDirectionType(ptr->Direction) << std::endl \
	 << std::setw(20) << "OffsetFlag:" << std::setw(6) << "(t)" << " " << getLfOffsetFlagType(ptr->OffsetFlag) << std::endl \
	 << std::setw(20) << "HedgeFlag:" << std::setw(6) << "(t)" << " " << getLfHedgeFlagType(ptr->HedgeFlag) << std::endl \
	 << std::setw(20) << "ForceCloseReason:" << std::setw(6) << "(t)" << " " << getLfForceCloseReasonType(ptr->ForceCloseReason) << std::endl \
	 << std::setw(20) << "StopPrice:" << std::setw(6) << "(d)" << " " << ptr->StopPrice << std::endl \
	 << std::setw(20) << "IsAutoSuspend:" << std::setw(6) << "(i)" << " " << (int)ptr->IsAutoSuspend << std::endl \
	 << std::setw(20) << "ContingentCondition:" << std::setw(6) << "(t)" << " " << getLfContingentConditionType(ptr->ContingentCondition) << std::endl \
	 << std::setw(20) << "MiscInfo:" << std::setw(6) << "(c30)" << " " << ptr->MiscInfo << std::endl \
	
#define PRINT_RTN_ORDER(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "ParticipantID:" << std::setw(6) << "(c11)" << " " << ptr->ParticipantID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "BusinessUnit:" << std::setw(6) << "(c21)" << " " << ptr->BusinessUnit << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c21)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c11)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "LimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LimitPrice << std::endl \
	 << std::setw(20) << "VolumeTraded:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeTraded << std::endl \
	 << std::setw(20) << "VolumeTotal:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeTotal << std::endl \
	 << std::setw(20) << "VolumeTotalOriginal:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeTotalOriginal << std::endl \
	 << std::setw(20) << "TimeCondition:" << std::setw(6) << "(t)" << " " << getLfTimeConditionType(ptr->TimeCondition) << std::endl \
	 << std::setw(20) << "VolumeCondition:" << std::setw(6) << "(t)" << " " << getLfVolumeConditionType(ptr->VolumeCondition) << std::endl \
	 << std::setw(20) << "OrderPriceType:" << std::setw(6) << "(t)" << " " << getLfOrderPriceTypeType(ptr->OrderPriceType) << std::endl \
	 << std::setw(20) << "Direction:" << std::setw(6) << "(t)" << " " << getLfDirectionType(ptr->Direction) << std::endl \
	 << std::setw(20) << "OffsetFlag:" << std::setw(6) << "(t)" << " " << getLfOffsetFlagType(ptr->OffsetFlag) << std::endl \
	 << std::setw(20) << "HedgeFlag:" << std::setw(6) << "(t)" << " " << getLfHedgeFlagType(ptr->HedgeFlag) << std::endl \
	 << std::setw(20) << "OrderStatus:" << std::setw(6) << "(t)" << " " << getLfOrderStatusType(ptr->OrderStatus) << std::endl \
	 << std::setw(20) << "RequestID:" << std::setw(6) << "(i)" << " " << (int)ptr->RequestID << std::endl \
	
#define PRINT_RTN_TRADE(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "BusinessUnit:" << std::setw(6) << "(c21)" << " " << ptr->BusinessUnit << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c21)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c11)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "TradeID:" << std::setw(6) << "(c21)" << " " << ptr->TradeID << std::endl \
	 << std::setw(20) << "OrderSysID:" << std::setw(6) << "(c31)" << " " << ptr->OrderSysID << std::endl \
	 << std::setw(20) << "ParticipantID:" << std::setw(6) << "(c11)" << " " << ptr->ParticipantID << std::endl \
	 << std::setw(20) << "ClientID:" << std::setw(6) << "(c21)" << " " << ptr->ClientID << std::endl \
	 << std::setw(20) << "Price:" << std::setw(6) << "(d)" << " " << ptr->Price << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(i)" << " " << (int)ptr->Volume << std::endl \
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c13)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "TradeTime:" << std::setw(6) << "(c13)" << " " << ptr->TradeTime << std::endl \
	 << std::setw(20) << "Direction:" << std::setw(6) << "(t)" << " " << getLfDirectionType(ptr->Direction) << std::endl \
	 << std::setw(20) << "OffsetFlag:" << std::setw(6) << "(t)" << " " << getLfOffsetFlagType(ptr->OffsetFlag) << std::endl \
	 << std::setw(20) << "HedgeFlag:" << std::setw(6) << "(t)" << " " << getLfHedgeFlagType(ptr->HedgeFlag) << std::endl \
	
#define PRINT_ORDER_ACTION(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c11)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c21)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "OrderSysID:" << std::setw(6) << "(c31)" << " " << ptr->OrderSysID << std::endl \
	 << std::setw(20) << "RequestID:" << std::setw(6) << "(i)" << " " << (int)ptr->RequestID << std::endl \
	 << std::setw(20) << "ActionFlag:" << std::setw(6) << "(c)" << " " << ptr->ActionFlag << std::endl \
	 << std::setw(20) << "LimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LimitPrice << std::endl \
	 << std::setw(20) << "VolumeChange:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeChange << std::endl \
	 << std::setw(20) << "KfOrderID:" << std::setw(6) << "(i)" << " " << (int)ptr->KfOrderID << std::endl \
	
#define PRINT_QRY_ACCOUNT(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	
#define PRINT_RSP_ACCOUNT(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "PreMortgage:" << std::setw(6) << "(d)" << " " << ptr->PreMortgage << std::endl \
	 << std::setw(20) << "PreCredit:" << std::setw(6) << "(d)" << " " << ptr->PreCredit << std::endl \
	 << std::setw(20) << "PreDeposit:" << std::setw(6) << "(d)" << " " << ptr->PreDeposit << std::endl \
	 << std::setw(20) << "preBalance:" << std::setw(6) << "(d)" << " " << ptr->preBalance << std::endl \
	 << std::setw(20) << "PreMargin:" << std::setw(6) << "(d)" << " " << ptr->PreMargin << std::endl \
	 << std::setw(20) << "Deposit:" << std::setw(6) << "(d)" << " " << ptr->Deposit << std::endl \
	 << std::setw(20) << "Withdraw:" << std::setw(6) << "(d)" << " " << ptr->Withdraw << std::endl \
	 << std::setw(20) << "FrozenMargin:" << std::setw(6) << "(d)" << " " << ptr->FrozenMargin << std::endl \
	 << std::setw(20) << "FrozenCash:" << std::setw(6) << "(d)" << " " << ptr->FrozenCash << std::endl \
	 << std::setw(20) << "FrozenCommission:" << std::setw(6) << "(d)" << " " << ptr->FrozenCommission << std::endl \
	 << std::setw(20) << "CurrMargin:" << std::setw(6) << "(d)" << " " << ptr->CurrMargin << std::endl \
	 << std::setw(20) << "CashIn:" << std::setw(6) << "(d)" << " " << ptr->CashIn << std::endl \
	 << std::setw(20) << "Commission:" << std::setw(6) << "(d)" << " " << ptr->Commission << std::endl \
	 << std::setw(20) << "CloseProfit:" << std::setw(6) << "(d)" << " " << ptr->CloseProfit << std::endl \
	 << std::setw(20) << "PositionProfit:" << std::setw(6) << "(d)" << " " << ptr->PositionProfit << std::endl \
	 << std::setw(20) << "Balance:" << std::setw(6) << "(d)" << " " << ptr->Balance << std::endl \
	 << std::setw(20) << "Available:" << std::setw(6) << "(d)" << " " << ptr->Available << std::endl \
	 << std::setw(20) << "WithdrawQuota:" << std::setw(6) << "(d)" << " " << ptr->WithdrawQuota << std::endl \
	 << std::setw(20) << "Reserve:" << std::setw(6) << "(d)" << " " << ptr->Reserve << std::endl \
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c9)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "Credit:" << std::setw(6) << "(d)" << " " << ptr->Credit << std::endl \
	 << std::setw(20) << "Mortgage:" << std::setw(6) << "(d)" << " " << ptr->Mortgage << std::endl \
	 << std::setw(20) << "ExchangeMargin:" << std::setw(6) << "(d)" << " " << ptr->ExchangeMargin << std::endl \
	 << std::setw(20) << "DeliveryMargin:" << std::setw(6) << "(d)" << " " << ptr->DeliveryMargin << std::endl \
	 << std::setw(20) << "ExchangeDeliveryMargin:" << std::setw(6) << "(d)" << " " << ptr->ExchangeDeliveryMargin << std::endl \
	 << std::setw(20) << "ReserveBalance:" << std::setw(6) << "(d)" << " " << ptr->ReserveBalance << std::endl \
	 << std::setw(20) << "Equity:" << std::setw(6) << "(d)" << " " << ptr->Equity << std::endl \
	 << std::setw(20) << "MarketValue:" << std::setw(6) << "(d)" << " " << ptr->MarketValue << std::endl \
	

/*****************************************/
// Macro to print struct content for ctp
/*****************************************/

#define PRINT_MD_CTP(ptr) ""\
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c9)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "ExchangeInstID:" << std::setw(6) << "(c64)" << " " << ptr->ExchangeInstID << std::endl \
	 << std::setw(20) << "LastPrice:" << std::setw(6) << "(d)" << " " << ptr->LastPrice << std::endl \
	 << std::setw(20) << "PreSettlementPrice:" << std::setw(6) << "(d)" << " " << ptr->PreSettlementPrice << std::endl \
	 << std::setw(20) << "PreClosePrice:" << std::setw(6) << "(d)" << " " << ptr->PreClosePrice << std::endl \
	 << std::setw(20) << "PreOpenInterest:" << std::setw(6) << "(d)" << " " << ptr->PreOpenInterest << std::endl \
	 << std::setw(20) << "OpenPrice:" << std::setw(6) << "(d)" << " " << ptr->OpenPrice << std::endl \
	 << std::setw(20) << "HighestPrice:" << std::setw(6) << "(d)" << " " << ptr->HighestPrice << std::endl \
	 << std::setw(20) << "LowestPrice:" << std::setw(6) << "(d)" << " " << ptr->LowestPrice << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(i)" << " " << (int)ptr->Volume << std::endl \
	 << std::setw(20) << "Turnover:" << std::setw(6) << "(d)" << " " << ptr->Turnover << std::endl \
	 << std::setw(20) << "OpenInterest:" << std::setw(6) << "(d)" << " " << ptr->OpenInterest << std::endl \
	 << std::setw(20) << "ClosePrice:" << std::setw(6) << "(d)" << " " << ptr->ClosePrice << std::endl \
	 << std::setw(20) << "SettlementPrice:" << std::setw(6) << "(d)" << " " << ptr->SettlementPrice << std::endl \
	 << std::setw(20) << "UpperLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->UpperLimitPrice << std::endl \
	 << std::setw(20) << "LowerLimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LowerLimitPrice << std::endl \
	 << std::setw(20) << "PreDelta:" << std::setw(6) << "(d)" << " " << ptr->PreDelta << std::endl \
	 << std::setw(20) << "CurrDelta:" << std::setw(6) << "(d)" << " " << ptr->CurrDelta << std::endl \
	 << std::setw(20) << "UpdateTime:" << std::setw(6) << "(c9)" << " " << ptr->UpdateTime << std::endl \
	 << std::setw(20) << "UpdateMillisec:" << std::setw(6) << "(i)" << " " << (int)ptr->UpdateMillisec << std::endl \
	 << std::setw(20) << "BidPrice1:" << std::setw(6) << "(d)" << " " << ptr->BidPrice1 << std::endl \
	 << std::setw(20) << "BidVolume1:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume1 << std::endl \
	 << std::setw(20) << "AskPrice1:" << std::setw(6) << "(d)" << " " << ptr->AskPrice1 << std::endl \
	 << std::setw(20) << "AskVolume1:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume1 << std::endl \
	 << std::setw(20) << "BidPrice2:" << std::setw(6) << "(d)" << " " << ptr->BidPrice2 << std::endl \
	 << std::setw(20) << "BidVolume2:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume2 << std::endl \
	 << std::setw(20) << "AskPrice2:" << std::setw(6) << "(d)" << " " << ptr->AskPrice2 << std::endl \
	 << std::setw(20) << "AskVolume2:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume2 << std::endl \
	 << std::setw(20) << "BidPrice3:" << std::setw(6) << "(d)" << " " << ptr->BidPrice3 << std::endl \
	 << std::setw(20) << "BidVolume3:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume3 << std::endl \
	 << std::setw(20) << "AskPrice3:" << std::setw(6) << "(d)" << " " << ptr->AskPrice3 << std::endl \
	 << std::setw(20) << "AskVolume3:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume3 << std::endl \
	 << std::setw(20) << "BidPrice4:" << std::setw(6) << "(d)" << " " << ptr->BidPrice4 << std::endl \
	 << std::setw(20) << "BidVolume4:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume4 << std::endl \
	 << std::setw(20) << "AskPrice4:" << std::setw(6) << "(d)" << " " << ptr->AskPrice4 << std::endl \
	 << std::setw(20) << "AskVolume4:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume4 << std::endl \
	 << std::setw(20) << "BidPrice5:" << std::setw(6) << "(d)" << " " << ptr->BidPrice5 << std::endl \
	 << std::setw(20) << "BidVolume5:" << std::setw(6) << "(i)" << " " << (int)ptr->BidVolume5 << std::endl \
	 << std::setw(20) << "AskPrice5:" << std::setw(6) << "(d)" << " " << ptr->AskPrice5 << std::endl \
	 << std::setw(20) << "AskVolume5:" << std::setw(6) << "(i)" << " " << (int)ptr->AskVolume5 << std::endl \
	
#define PRINT_QRY_POS_CTP(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c13)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	
#define PRINT_RSP_POS_CTP(ptr) ""\
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "*YdPosition:"<< std::setw(6) << "(i)" << " " << ptr->Position - ptr->TodayPosition << "	(Position-TodayPosition)" << std::endl \
	 << std::setw(20) << "Position:" << std::setw(6) << "(i)" << " " << ptr->Position << std::endl \
	 << std::setw(20) << "TodayPosition:" << std::setw(6) << "(i)" << " " << ptr->TodayPosition << std::endl \
	 << std::setw(20) << "Position:" << std::setw(6) << "(i)" << " " << (int)ptr->Position << std::endl \
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c13)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "PositionCost:" << std::setw(6) << "(d)" << " " << ptr->PositionCost << std::endl \
	 << std::setw(20) << "HedgeFlag:" << std::setw(6) << "(t)" << " " << getLfHedgeFlagType(ptr->HedgeFlag) << std::endl \
	 << std::setw(20) << "PosiDirection:" << std::setw(6) << "(t)" << " " << getLfPosiDirectionType(ptr->PosiDirection) << std::endl \
	
#define PRINT_ORDER_CTP(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c19)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "BusinessUnit:" << std::setw(6) << "(c21)" << " " << ptr->BusinessUnit << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c13)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "LimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LimitPrice << std::endl \
	 << std::setw(20) << "VolumeTotalOriginal:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeTotalOriginal << std::endl \
	 << std::setw(20) << "MinVolume:" << std::setw(6) << "(i)" << " " << (int)ptr->MinVolume << std::endl \
	 << std::setw(20) << "TimeCondition:" << std::setw(6) << "(t)" << " " << getLfTimeConditionType(ptr->TimeCondition) << std::endl \
	 << std::setw(20) << "VolumeCondition:" << std::setw(6) << "(t)" << " " << getLfVolumeConditionType(ptr->VolumeCondition) << std::endl \
	 << std::setw(20) << "OrderPriceType:" << std::setw(6) << "(t)" << " " << getLfOrderPriceTypeType(ptr->OrderPriceType) << std::endl \
	 << std::setw(20) << "Direction:" << std::setw(6) << "(t)" << " " << getLfDirectionType(ptr->Direction) << std::endl \
	 << std::setw(20) << "CombOffsetFlag:" << std::setw(6) << "(c5)" << " " << ptr->CombOffsetFlag << std::endl \
	 << std::setw(20) << "CombHedgeFlag:" << std::setw(6) << "(c5)" << " " << ptr->CombHedgeFlag << std::endl \
	 << std::setw(20) << "ForceCloseReason:" << std::setw(6) << "(t)" << " " << getLfForceCloseReasonType(ptr->ForceCloseReason) << std::endl \
	 << std::setw(20) << "StopPrice:" << std::setw(6) << "(d)" << " " << ptr->StopPrice << std::endl \
	 << std::setw(20) << "IsAutoSuspend:" << std::setw(6) << "(i)" << " " << (int)ptr->IsAutoSuspend << std::endl \
	 << std::setw(20) << "ContingentCondition:" << std::setw(6) << "(t)" << " " << getLfContingentConditionType(ptr->ContingentCondition) << std::endl \
	
#define PRINT_RTN_ORDER_CTP(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "ParticipantID:" << std::setw(6) << "(c11)" << " " << ptr->ParticipantID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c13)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "BusinessUnit:" << std::setw(6) << "(c21)" << " " << ptr->BusinessUnit << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c13)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "LimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LimitPrice << std::endl \
	 << std::setw(20) << "VolumeTraded:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeTraded << std::endl \
	 << std::setw(20) << "VolumeTotal:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeTotal << std::endl \
	 << std::setw(20) << "VolumeTotalOriginal:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeTotalOriginal << std::endl \
	 << std::setw(20) << "TimeCondition:" << std::setw(6) << "(t)" << " " << getLfTimeConditionType(ptr->TimeCondition) << std::endl \
	 << std::setw(20) << "VolumeCondition:" << std::setw(6) << "(t)" << " " << getLfVolumeConditionType(ptr->VolumeCondition) << std::endl \
	 << std::setw(20) << "OrderPriceType:" << std::setw(6) << "(t)" << " " << getLfOrderPriceTypeType(ptr->OrderPriceType) << std::endl \
	 << std::setw(20) << "Direction:" << std::setw(6) << "(t)" << " " << getLfDirectionType(ptr->Direction) << std::endl \
	 << std::setw(20) << "CombOffsetFlag:" << std::setw(6) << "(c5)" << " " << ptr->CombOffsetFlag << std::endl \
	 << std::setw(20) << "CombHedgeFlag:" << std::setw(6) << "(c5)" << " " << ptr->CombHedgeFlag << std::endl \
	 << std::setw(20) << "OrderStatus:" << std::setw(6) << "(t)" << " " << getLfOrderStatusType(ptr->OrderStatus) << std::endl \
	 << std::setw(20) << "RequestID:" << std::setw(6) << "(i)" << " " << (int)ptr->RequestID << std::endl \
	
#define PRINT_RTN_TRADE_CTP(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c13)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "BusinessUnit:" << std::setw(6) << "(c21)" << " " << ptr->BusinessUnit << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c13)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "TradeID:" << std::setw(6) << "(c21)" << " " << ptr->TradeID << std::endl \
	 << std::setw(20) << "OrderSysID:" << std::setw(6) << "(c21)" << " " << ptr->OrderSysID << std::endl \
	 << std::setw(20) << "ParticipantID:" << std::setw(6) << "(c11)" << " " << ptr->ParticipantID << std::endl \
	 << std::setw(20) << "ClientID:" << std::setw(6) << "(c11)" << " " << ptr->ClientID << std::endl \
	 << std::setw(20) << "Price:" << std::setw(6) << "(d)" << " " << ptr->Price << std::endl \
	 << std::setw(20) << "Volume:" << std::setw(6) << "(i)" << " " << (int)ptr->Volume << std::endl \
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c13)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "TradeTime:" << std::setw(6) << "(c9)" << " " << ptr->TradeTime << std::endl \
	 << std::setw(20) << "Direction:" << std::setw(6) << "(t)" << " " << getLfDirectionType(ptr->Direction) << std::endl \
	 << std::setw(20) << "OffsetFlag:" << std::setw(6) << "(t)" << " " << getLfOffsetFlagType(ptr->OffsetFlag) << std::endl \
	 << std::setw(20) << "HedgeFlag:" << std::setw(6) << "(t)" << " " << getLfHedgeFlagType(ptr->HedgeFlag) << std::endl \
	
#define PRINT_ORDER_ACTION_CTP(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c13)" << " " << ptr->InvestorID << std::endl \
	 << std::setw(20) << "InstrumentID:" << std::setw(6) << "(c31)" << " " << ptr->InstrumentID << std::endl \
	 << std::setw(20) << "ExchangeID:" << std::setw(6) << "(c9)" << " " << ptr->ExchangeID << std::endl \
	 << std::setw(20) << "UserID:" << std::setw(6) << "(c16)" << " " << ptr->UserID << std::endl \
	 << std::setw(20) << "OrderRef:" << std::setw(6) << "(c13)" << " " << ptr->OrderRef << std::endl \
	 << std::setw(20) << "OrderSysID:" << std::setw(6) << "(c21)" << " " << ptr->OrderSysID << std::endl \
	 << std::setw(20) << "RequestID:" << std::setw(6) << "(i)" << " " << (int)ptr->RequestID << std::endl \
	 << std::setw(20) << "ActionFlag:" << std::setw(6) << "(c)" << " " << ptr->ActionFlag << std::endl \
	 << std::setw(20) << "LimitPrice:" << std::setw(6) << "(d)" << " " << ptr->LimitPrice << std::endl \
	 << std::setw(20) << "VolumeChange:" << std::setw(6) << "(i)" << " " << (int)ptr->VolumeChange << std::endl \
	
#define PRINT_QRY_ACCOUNT_CTP(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "InvestorID:" << std::setw(6) << "(c13)" << " " << ptr->InvestorID << std::endl \
	
#define PRINT_RSP_ACCOUNT_CTP(ptr) ""\
	 << std::setw(20) << "BrokerID:" << std::setw(6) << "(c11)" << " " << ptr->BrokerID << std::endl \
	 << std::setw(20) << "AccountID:" << std::setw(6) << "(c13)" << " " << ptr->AccountID << std::endl \
	 << std::setw(20) << "PreMortgage:" << std::setw(6) << "(d)" << " " << ptr->PreMortgage << std::endl \
	 << std::setw(20) << "PreCredit:" << std::setw(6) << "(d)" << " " << ptr->PreCredit << std::endl \
	 << std::setw(20) << "PreDeposit:" << std::setw(6) << "(d)" << " " << ptr->PreDeposit << std::endl \
	 << std::setw(20) << "PreBalance:" << std::setw(6) << "(d)" << " " << ptr->PreBalance << std::endl \
	 << std::setw(20) << "PreMargin:" << std::setw(6) << "(d)" << " " << ptr->PreMargin << std::endl \
	 << std::setw(20) << "Deposit:" << std::setw(6) << "(d)" << " " << ptr->Deposit << std::endl \
	 << std::setw(20) << "Withdraw:" << std::setw(6) << "(d)" << " " << ptr->Withdraw << std::endl \
	 << std::setw(20) << "FrozenMargin:" << std::setw(6) << "(d)" << " " << ptr->FrozenMargin << std::endl \
	 << std::setw(20) << "FrozenCash:" << std::setw(6) << "(d)" << " " << ptr->FrozenCash << std::endl \
	 << std::setw(20) << "FrozenCommission:" << std::setw(6) << "(d)" << " " << ptr->FrozenCommission << std::endl \
	 << std::setw(20) << "CurrMargin:" << std::setw(6) << "(d)" << " " << ptr->CurrMargin << std::endl \
	 << std::setw(20) << "CashIn:" << std::setw(6) << "(d)" << " " << ptr->CashIn << std::endl \
	 << std::setw(20) << "Commission:" << std::setw(6) << "(d)" << " " << ptr->Commission << std::endl \
	 << std::setw(20) << "CloseProfit:" << std::setw(6) << "(d)" << " " << ptr->CloseProfit << std::endl \
	 << std::setw(20) << "PositionProfit:" << std::setw(6) << "(d)" << " " << ptr->PositionProfit << std::endl \
	 << std::setw(20) << "Balance:" << std::setw(6) << "(d)" << " " << ptr->Balance << std::endl \
	 << std::setw(20) << "Available:" << std::setw(6) << "(d)" << " " << ptr->Available << std::endl \
	 << std::setw(20) << "WithdrawQuota:" << std::setw(6) << "(d)" << " " << ptr->WithdrawQuota << std::endl \
	 << std::setw(20) << "Reserve:" << std::setw(6) << "(d)" << " " << ptr->Reserve << std::endl \
	 << std::setw(20) << "TradingDay:" << std::setw(6) << "(c9)" << " " << ptr->TradingDay << std::endl \
	 << std::setw(20) << "Credit:" << std::setw(6) << "(d)" << " " << ptr->Credit << std::endl \
	 << std::setw(20) << "Mortgage:" << std::setw(6) << "(d)" << " " << ptr->Mortgage << std::endl \
	 << std::setw(20) << "ExchangeMargin:" << std::setw(6) << "(d)" << " " << ptr->ExchangeMargin << std::endl \
	 << std::setw(20) << "DeliveryMargin:" << std::setw(6) << "(d)" << " " << ptr->DeliveryMargin << std::endl \
	 << std::setw(20) << "ExchangeDeliveryMargin:" << std::setw(6) << "(d)" << " " << ptr->ExchangeDeliveryMargin << std::endl \
	 << std::setw(20) << "ReserveBalance:" << std::setw(6) << "(d)" << " " << ptr->ReserveBalance << std::endl \
	 << std::setw(20) << "*Equity:"<< std::setw(6) << "(d)" << " " <<ptr->PreBalance - ptr->PreCredit - ptr->PreMortgage + ptr->Mortgage - ptr->Withdraw + ptr->Deposit + ptr->CloseProfit + ptr->PositionProfit + ptr->CashIn - ptr->Commission <<	"(PreBalance - PreCredit - PreMortgage + Mortgage - Withdraw + Deposit + CloseProfit + PositionProfit + CashIn - Commission )"	 << std::endl;\


inline void printData(const void* data, short msg_type)
{
	switch(msg_type)
	{
		case MSG_TYPE_LF_MD:
		{
			LFMarketDataField* ptr = (LFMarketDataField*)data;
			std::cout << PRINT_MD(ptr);
			break;
		}
		case MSG_TYPE_LF_L2_MD:
		{
			LFL2MarketDataField* ptr = (LFL2MarketDataField*)data;
			std::cout << PRINT_L2_MD(ptr);
			break;
		}
		case MSG_TYPE_LF_L2_INDEX:
		{
			LFL2IndexField* ptr = (LFL2IndexField*)data;
			std::cout << PRINT_L2_INDEX(ptr);
			break;
		}
		case MSG_TYPE_LF_L2_ORDER:
		{
			LFL2OrderField* ptr = (LFL2OrderField*)data;
			std::cout << PRINT_L2_ORDER(ptr);
			break;
		}
		case MSG_TYPE_LF_L2_TRADE:
		{
			LFL2TradeField* ptr = (LFL2TradeField*)data;
			std::cout << PRINT_L2_TRADE(ptr);
			break;
		}
		case MSG_TYPE_LF_BAR_MD:
		{
			LFBarMarketDataField* ptr = (LFBarMarketDataField*)data;
			std::cout << PRINT_BAR_MD(ptr);
			break;
		}
		case MSG_TYPE_LF_QRY_POS:
		{
			LFQryPositionField* ptr = (LFQryPositionField*)data;
			std::cout << PRINT_QRY_POS(ptr);
			break;
		}
		case MSG_TYPE_LF_RSP_POS:
		{
			LFRspPositionField* ptr = (LFRspPositionField*)data;
			std::cout << PRINT_RSP_POS(ptr);
			break;
		}
		case MSG_TYPE_LF_ORDER:
		{
			LFInputOrderField* ptr = (LFInputOrderField*)data;
			std::cout << PRINT_ORDER(ptr);
			break;
		}
		case MSG_TYPE_LF_RTN_ORDER:
		{
			LFRtnOrderField* ptr = (LFRtnOrderField*)data;
			std::cout << PRINT_RTN_ORDER(ptr);
			break;
		}
		case MSG_TYPE_LF_RTN_TRADE:
		{
			LFRtnTradeField* ptr = (LFRtnTradeField*)data;
			std::cout << PRINT_RTN_TRADE(ptr);
			break;
		}
		case MSG_TYPE_LF_ORDER_ACTION:
		{
			LFOrderActionField* ptr = (LFOrderActionField*)data;
			std::cout << PRINT_ORDER_ACTION(ptr);
			break;
		}
		case MSG_TYPE_LF_QRY_ACCOUNT:
		{
			LFQryAccountField* ptr = (LFQryAccountField*)data;
			std::cout << PRINT_QRY_ACCOUNT(ptr);
			break;
		}
		case MSG_TYPE_LF_RSP_ACCOUNT:
		{
			LFRspAccountField* ptr = (LFRspAccountField*)data;
			std::cout << PRINT_RSP_ACCOUNT(ptr);
			break;
		}
		case MSG_TYPE_LF_MD_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcDepthMarketDataField* ptr = (CThostFtdcDepthMarketDataField*)data;
			std::cout << PRINT_MD_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_QRY_POS_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcQryInvestorPositionField* ptr = (CThostFtdcQryInvestorPositionField*)data;
			std::cout << PRINT_QRY_POS_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_RSP_POS_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcInvestorPositionField* ptr = (CThostFtdcInvestorPositionField*)data;
			std::cout << PRINT_RSP_POS_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_ORDER_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcInputOrderField* ptr = (CThostFtdcInputOrderField*)data;
			std::cout << PRINT_ORDER_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_RTN_ORDER_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcOrderField* ptr = (CThostFtdcOrderField*)data;
			std::cout << PRINT_RTN_ORDER_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_RTN_TRADE_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcTradeField* ptr = (CThostFtdcTradeField*)data;
			std::cout << PRINT_RTN_TRADE_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_ORDER_ACTION_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcInputOrderActionField* ptr = (CThostFtdcInputOrderActionField*)data;
			std::cout << PRINT_ORDER_ACTION_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_QRY_ACCOUNT_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcQryTradingAccountField* ptr = (CThostFtdcQryTradingAccountField*)data;
			std::cout << PRINT_QRY_ACCOUNT_CTP(ptr);
			break;
		}
		case MSG_TYPE_LF_RSP_ACCOUNT_CTP:
		{
			using namespace LF_UTIL_PRINTER_CTP;
			CThostFtdcTradingAccountField* ptr = (CThostFtdcTradingAccountField*)data;
			std::cout << PRINT_RSP_ACCOUNT_CTP(ptr);
			break;
		}
	}
}

#endif
