export const columns: AntTableColumns = [
    {
        title: '备注',
        dataIndex: 'accountName',
        align: 'left',
        sorter: true,
        width: 80,
        fixed: 'left',
    },
    {
        title: '账户',
        dataIndex: 'name',
        align: 'left',
        sorter: true,
        width: 160,
        fixed: 'left',
    },
    {
        title: '状态',
        dataIndex: 'stateStatus',
        align: 'left',
        sorter: true,
        width: 80,
        fixed: 'left',
    },
    {
        title: '进程',
        dataIndex: 'processStatus',
        align: 'center',
        sorter: true,
        width: 60,
        fixed: 'left',
    },
    {
        title: '浮动盈亏',
        dataIndex: 'unrealizedPnl',
        align: 'right',
        sorter: true,
        width: 110,
    },
    {
        title: '可用资金',
        dataIndex: 'avail',
        align: 'right',
        sorter: true,
        width: 110,
    },
    {
        title: '市值',
        dataIndex: 'marketValue',
        align: 'right',
        sorter: true,
        width: 110,
    },
    {
        title: '保证金',
        dataIndex: 'margin',
        align: 'right',
        sorter: true,
        width: 110,
    },
    {
        title: '操作',
        dataIndex: 'actions',
        align: 'right',
        width: 140,
        fixed: 'right',
    },
];
