export const columns: AntTableColumns = [
    {
        title: '备注',
        dataIndex: 'accountName',
        align: 'left',
        sorter: true,
        fixed: 'left',
        width: 80,
    },
    {
        title: '账户',
        dataIndex: 'accountId',
        align: 'left',
        sorter: true,
        fixed: 'left',
        width: 90,
    },
    {
        title: '柜台',
        dataIndex: 'sourceId',
        align: 'left',
        sorter: true,
        fixed: 'left',
        width: 60,
    },
    {
        title: '状态',
        dataIndex: 'stateStatus',
        align: 'left',
        sorter: true,
        width: 80,
    },
    {
        title: '进程',
        dataIndex: 'processStatus',
        align: 'center',
        sorter: true,
        width: 60,
    },
    {
        title: '浮动盈亏',
        dataIndex: 'unrealizedPnl',
        align: 'right',
        sorter: true,
        width: 90,
    },
    {
        title: '可用资金',
        dataIndex: 'avail',
        align: 'right',
        sorter: true,
        width: 90,
    },
    {
        title: '市值',
        dataIndex: 'marketValue',
        align: 'right',
        sorter: true,
        width: 90,
    },
    {
        title: '保证金',
        dataIndex: 'margin',
        align: 'right',
        sorter: true,
        width: 90,
    },
    {
        title: '操作',
        dataIndex: 'actions',
        align: 'right',
        width: 140,
        fixed: 'right',
    },
];
